### ISSUE TITLE
Can't see that go build is building an executable

### ISSUE THREAD

**Issue by 7k50** [4cq2/mech#1]
Last time I tried to build mech was in April 2022.

Now, with Go 1.20.2 installed on my Mac, I am trying to build Bandcamp once more.

However, when running `go build` inside of the `/bandcamp` directory, this will retrieve some stuff to my Go `/pkg/mod/cache/download` directory, but I can't see that any `bandcamp` executable is built in the `/bandcamp` directory.

I'm wondering if building Bandcamp is supposed to work as intended, in the current version of the repo?

I'm a Go beginner, so I'm not sure how to troubleshoot.

**Comment by 4cq2** [comment]
you're having trouble because `bandcamp` is the folder for the Bandcamp package, not a Bandcamp tool. I removed the tool some time ago, because I didn't personally use it, and it was becoming a maintenance burden. What you would be looking for is `cmd/bandcamp` if it existed. Which at the time of your post it did not. I have now restored the Bandcamp tool, however I dont offer any guarantees on it, including that it will remain in the repository.
