### ISSUE TITLE
Window immediately closes after I input the "go build" command

### ISSUE THREAD

**Issue by LunaLanaLuana** [4cq2/mech#6]
I downloaded both the Go programming language and the Mech Zip, I reached the mech-main/cmd/youtube folder, and inputted "go build". After that, it seems like the corresponding application opens for a second and then closes, and I'm not sure how to proceed.

**Comment by 4cq2** [comment]
as previously mentioned, I dont provide free support. I know that might be different from your typical GitHub experience, but if you have an issue, you'll either need to pay for support, or try to figure out the problem yourself. If you want support, contact me:

https://github.com/4cq2/mech#contact

otherwise good luck.
